version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: default
    filename: "logs/uvicorn.log"
    when: "midnight"
    interval: 1
    backupCount: 7
    encoding: "utf-8"

loggers:
  uvicorn:
    handlers: [file]
    level: INFO
    propagate: True

root:
  handlers: [file]
  level: INFO
